[package]
name = "blockora-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
chrono = "0.4"

[[bin]]
name = "blockora"
path = "cli/main.rs"
